devBundle=1.21.8-R0.1-SNAPSHOT
javaRelease=21
mappings=spigot

CompoundTag=v1_21_5
CraftItemStack=v1_21_8
DataComponents=v1_21_3
DataFixer=v1_17_R1
ListTag=v1_21_5
NBTUtilsModern=v1_21_5
NbtIo=v1_20_R3
