devBundle=26.1.1.build.29-alpha
javaRelease=21
mappings=mojang
javaToolchain=25

CompoundTag=v1_21_5
CraftItemStack=v26_1_1
DataComponents=v1_21_11
DataFixer=v1_17_R1
ListTag=v1_21_5
NBTUtilsModern=v1_21_5
NbtIo=v1_20_R3
